# Generated by Django 6.0.7 on 2026-07-29 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('continent', models.CharField(choices=[('africa', 'Afrique'), ('america', 'Amerique'), ('asia', 'Asie'), ('europe', 'Europe'), ('oceania', 'Oceanie')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('best_period', models.CharField(blank=True, max_length=100)),
                ('average_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['country', 'city'],
                'constraints': [models.UniqueConstraint(fields=('city', 'country'), name='unique_destination_city_country')],
            },
        ),
        migrations.CreateModel(
            name='TravelWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute')], default='medium', max_length=10)),
                ('desired_period', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('visited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='travel.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_wishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'destination'), name='unique_user_destination_wish')],
            },
        ),
    ]
